In [1]:
import numpy as np

In [13]:
#1
arr=np.zeros(10)
arr[4]=1
print(arr.astype(int))
print((np.arange(10)==4).astype(int))

[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


In [11]:
#2
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
#3
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [17]:
#4
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
#5
arr=np.array([1,2,0,0,4,0])
np.argwhere(arr!=0)

array([[0],
       [1],
       [4]])

In [24]:
#6
np.random.rand(3,3,3)

array([[[0.4150682 , 0.17058448, 0.25467428],
        [0.38609171, 0.09609935, 0.45171014],
        [0.41662892, 0.18819001, 0.12392492]],

       [[0.3408408 , 0.78802961, 0.09383164],
        [0.69982418, 0.50939557, 0.74912531],
        [0.14035858, 0.94780614, 0.95229187]],

       [[0.46601576, 0.23035949, 0.25239467],
        [0.40604189, 0.88373078, 0.85263905],
        [0.37249087, 0.954715  , 0.77880575]]])

In [30]:
#7
arr=np.random.rand(10,10)
print(arr)
arr.min(),arr.max()

[[0.43708102 0.57871924 0.05432426 0.44058533 0.35268334 0.6469785
  0.9078356  0.27433011 0.67142176 0.99070003]
 [0.71790831 0.49004983 0.57357307 0.51414331 0.84155428 0.89876896
  0.89585994 0.09406433 0.1954487  0.30435029]
 [0.76058938 0.60493766 0.05000337 0.79120536 0.56151203 0.38919882
  0.03738607 0.42679912 0.08666297 0.79643622]
 [0.8479696  0.7694877  0.65927591 0.47316775 0.14093002 0.30591512
  0.11083208 0.86139089 0.2404673  0.41349985]
 [0.89340053 0.41859073 0.86213732 0.75198203 0.37754978 0.51033448
  0.7432761  0.44045522 0.49211509 0.48226864]
 [0.67777817 0.34952612 0.2035498  0.57058365 0.70870409 0.86504772
  0.74282712 0.96274714 0.84475116 0.20714014]
 [0.85260991 0.35641301 0.73849035 0.47747398 0.65186888 0.10361171
  0.95334696 0.18032156 0.99674418 0.92253219]
 [0.58933528 0.00759659 0.17445194 0.67734743 0.50411596 0.63078187
  0.34547723 0.48753085 0.67156464 0.12691692]
 [0.77728045 0.83711614 0.98550728 0.2825745  0.53344587 0.99839547
  0.315078   

(0.004083432658898212, 0.9983954709124324)

In [34]:
#8
arr=np.ones((8,8)).astype(int)
arr[1:-1,1:-1]=0
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
